sudo: required
services:
  - docker

before_install:
  - docker build -t agrapine/docker-react -f Dockerfile.dev .

script:
  - docker run agrapine/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-788698227489"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"
